let mods = {
  'Fitted': 'Fitted',
  'Link': 'Link',
  'Circular': 'Circular',
  'Flipped': 'Flipped',
  'Rotated': 'Rotated',
  'Bordered': 'Bordered',
  'Inverted': 'Inverted',
  'Colors': 'Colors',
  'Sizes': 'Sizes',
  'outline': 'outline',
  'slash': 'slash',
  'square': 'square',
  'forward': 'forward',
  'alternate': 'alternate',
  'telephone': 'telephone',
  'circle': 'circle',
  'share': 'share',
  'bookmark': 'bookmark',
  'horizontal': 'horizontal',
  'vertical': 'vertical',
  'double': 'double',
  'stroke': 'stroke',
  'down': 'down',
  'up': 'up',
  'left': 'left',
  'right': 'right',
};

export default mods;
